name: 编译-Onnxruntime-Win32

on:
    workflow_dispatch:
        inputs:

            version:
                description: '源码版本 (Search)'
                required: true
                default: '1.16.3'

            build:
                description: '发布版本 (Release Debug MinSizeRel RelWithDebInfo)'
                required: true
                default: 'Release'

            library:
                description: '是否编译动态库 (OFF ON)'
                required: true
                default: 'OFF'

            cpu:
                description: '生成架构 (x64 || win32)'
                required: true
                default: 'x64'

env:

    CONFIG_VERSION: ${{ github.event.inputs.version }}
    CONFIG_LIBRARY: ${{ github.event.inputs.library }}
    CONFIG_BUILD: ${{ github.event.inputs.build }}
    CONFIG_CPU: ${{ github.event.inputs.cpu }}

jobs:

    build:
        runs-on: windows-2022

        steps:
            - name: '安装环境 Cmake'
              uses: jwlawson/actions-setup-cmake@v1.14.2
            
            - name: '拉取源码'
              run: |
                  git clone -b rel-$Env:CONFIG_VERSION --recursive https://github.com/Microsoft/onnxruntime

            - name: '更新源码'
              run: |
                  cd onnxruntime
                  git submodule update --init --recursive

            - name: '编译，启动！'
              run: |
                  cd onnxruntime
                  .\build.bat --update --config $Env:CONFIG_BUILD --skip_tests --parallel
                  cd build
                  ls
                  cd Windows
                  ls
                  cd $Env:CONFIG_BUILD
                  ls
                  cd lib
                  ls

            - name: '编译，完成！'
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: 编译-Onnxruntime-Win32
                  path: ${{ github.workspace }}/onnxruntime/build/Windows/${{ github.event.inputs.build }}/onnxruntime_*
