name: 编译-Onnxruntime-Win32

on:
    workflow_dispatch:
        inputs:

            version:
                description: '源码版本 (Search)'
                required: true
                default: '1.12.1'

            build:
                description: '发布版本 (Release Debug)'
                required: true
                default: 'Release'

            library:
                description: '是否编译动态库 (OFF ON)'
                required: true
                default: 'OFF'

            cpu:
                description: '生成架构 (x64 || win32)'
                required: true
                default: 'x64'

env:

    CONFIG_VERSION: ${{ github.event.inputs.version }}
    CONFIG_LIBRARY: ${{ github.event.inputs.library }}
    CONFIG_BUILD: ${{ github.event.inputs.build }}
    CONFIG_CPU: ${{ github.event.inputs.cpu }}

    ONNXRUNTIME_CODE_URL: https://github.com/microsoft/onnxruntime/archive/refs/tags/${{ github.event.inputs.version }}.zip

    ONNXRUNTIME_DIR_NAME: onnxruntime-${{ github.event.inputs.version }}

jobs:

    build:
        runs-on: windows-2019

        steps:
            - name: '安装环境 Cmake'
              uses: jwlawson/actions-setup-cmake@v1.14.2
            
            - name: '下载源码'
              run: |
                  Invoke-RestMethod -Uri $Env:ONNXRUNTIME_CODE_URL -OutFile code.zip

            - name: '解压源码'
              run: |
                  Expand-Archive -LiteralPath code.zip -DestinationPath temp -PassThru
                  rm code.zip

            - name: '编译，启动！'
              run: |
                  cd temp
                  cd $Env:ONNXRUNTIME_DIR_NAME
                  build.bat --config $CONFIG_BUILD --skip_tests --parallel

            - name: '编译，完成！'
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: 编译-Onnxruntime-Win32
                  path: ${{ github.workspace }}/temp/$Env:ONNXRUNTIME_DIR_NAME/build
