name: Build Crypto++ MSVC (MT & LTO)

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get latest Crypto++ tag
        shell: bash
        run: |
          # 获取最新的 tag 名称
          LATEST_TAG=$(curl -s https://api.github.com/repos/weidai11/cryptopp/tags | jq -r '.[0].name')
          echo "Selected Tag: $LATEST_TAG"
          # 克隆指定 tag
          git clone --depth 1 --branch $LATEST_TAG https://github.com/weidai11/cryptopp.git .

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build x86 (Release MT + LTO)
        run: |
          MSBuild cryptest.sln `
            /maxcpucount:1 `
            /p:Configuration=Release `
            /p:Platform="Win32" `
            /p:RuntimeLibrary=MultiThreaded `
            /p:WholeProgramOptimization=true `
            /p:PlatformToolset=v143

      - name: Build x64 (Release MT + LTO)
        run: |
          MSBuild cryptest.sln `
            /maxcpucount:1 `
            /p:Configuration=Release `
            /p:Platform="x64" `
            /p:RuntimeLibrary=MultiThreaded `
            /p:WholeProgramOptimization=true `
            /p:PlatformToolset=v143

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cryptopp-msvc-mt-lto
          path: |
            Win32/Output/Release/*.lib
            x64/Output/Release/*.lib
            *.h
