name: 编译-Opencv

on:
  workflow_dispatch:
   inputs:

      version:
        description: '源码版本'
        required: true
        default: '4.8.0'

      library:
        description: '是否编译动态库'
        required: true
        default: 'OFF'

env:
   CODE_URL: https://github.com/opencv/opencv/archive/refs/tags/${{github.event.inputs.version}}.zip
   SHARE_LIBRARY: ${{github.event.inputs.library}}

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: '下载源码'
        run: wget $CODE_URL -O code.zip

      - name: '解压源码'
        run: unzip -d temp code.zip

      - name: '准备工作'
        run: cd temp && mkdir build && cd build

      - name: '编译，启动！'
        run: cmake ..
