name: Opencv

on:
  workflow_dispatch
   inputs:

      version:
        description: '源码版本'
        required: true
        default: '4.8.0'

      library:
        description: '是否编译动态库'
        required: true
        default: false

env:
   DOWNLOAD_URL: https://github.com/opencv/opencv/archive/refs/tags/${INPUT_VERSION}.zip

jobs:

  build:
    runs-on: ubuntu-18.04

    steps1:
      - name: "准备工作"
        run: apt update && apt upgrade && apt install unzip -y && apt install cmake -y

    steps1:
      - name: "获取源码"
        run: curl ${DOWNLOAD_URL} -o code.zip && mkdir temp && unzip -d ./temp code.zip

    steps3:
      - name: "准备编译"
        run: cd temp && mkdir build && cd build

    steps4:
      - name: "编译"
        run: cmake ..
