# Opencv Linux

name: opencv-linux

on:
  workflow_dispatch:
    inputs:
      version:
        description: "版本号"
        required: true

env:
  OPENCV_VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 安装Cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: "latest"

    - name: 测试CMake
      run: cmake --version

    - name: 检出Opencv源代码
      uses: actions/checkout@v4
      with:
        repository: opencv/opencv
        ref: ${{ env.OPENCV_VERSION }}

    - name: 创建Cmake临时文件夹
      run: mkdir build

    - name: 修复Openjpeg库
      run: sed -i 's/define OPJ_API    __attribute__ ((visibility ("hidden")))/define OPJ_API    __attribute__ ((visibility ("default")))/g' 3rdparty/openjpeg/openjp2/openjpeg.h

    - name: 编译，启动！
      run: cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TIFF=OFF -DBUILD_JASPER=OFF -DBUILD_ITT=OFF -DBUILD_OPENEXR=OFF -DBUILD_ILMIMF=OFF -DBUILD_JPEG=ON -DBUILD_OPENJPEG=ON -DBUILD_WEBP=ON -DBUILD_PNG=ON -DWITH_PNG=ON -DBUILD_ZLIB=ON -DWITH_TIFF=OFF -DWITH_ILMIMF=OFF -DWITH_OPENEXR=OFF -DBUILD_PROTOBUF=OFF -DWITH_PROTOBUF=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_ts=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_videostab=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_gpu=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_nonfree=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_contrib=OFF -DBUILD_opencv_gapi=OFF -DBUILD_opencv_highgui=OFF -DBUILD_opencv_videoio=OFF -DBUILD_opencv_lengcy=OFF -DBUILD_opencv_ittnotify=OFF -DBUILD_WITH_DEBUG_INFO=OFF -DWITH_QT=OFF -DWITH_1394=OFF -DWITH_FFMPEG=OFF -DWITH_GTK=OFF -DWITH_VTK=OFF -DWITH_FFMPEG=OFF -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_QUIRC=OFF -DWITH_MSMF=OFF -DWITH_GSTREAMER=OFF -DWITH_V4L=OFF -DWITH_ADE=OFF -DWITH_PVAPI=OFF -DWITH_CUFFT=OFF -DWITH_EIGEN=OFF -DWITH_GIGEAPI=OFF -DWITH_LIBV4L=OFF -DWITH_OPENCLAMDFFT=OFF -DWITH_OPENCLAMDBLAS=OFF -DWITH_OPENCL_SVM=OFF -DBUILD_TBB=OFF -DWITH_IPP=OFF -DWITH_HPX=OFF -DWITH_PTHREADS_PF=ON -DWITH_OPENMP=OFF -DPARALLEL_ENABLE_PLUGINS=OFF -DVIDEOIO_ENABLE_PLUGINS=OFF -DHIGHGUI_ENABLE_PLUGINS=OFF -DBUILD_opencv_world=OFF -DWITH_JASPER=OFF -DWITH_OPENJPEG=ON -DWITH_JPEG=ON -D CMAKE_INSTALL_PREFIX=./install ..

    - name: 处理文件格式
      run: 